import { Brand, Category, Product } from '@/types';

export const brands: Brand[] = [
  { id: 'berger', name: 'Berger', logo: '/images/brands/berger.png', description: 'Premium quality paints for every surface', productCount: 45 },
  { id: 'brighto', name: 'Brighto', logo: '/images/brands/brighto.png', description: 'Bright and lasting colors for your home', productCount: 32 },
  { id: 'choice', name: 'Choice', logo: '/images/brands/choice.png', description: 'Your choice for quality paints', productCount: 28 },
  { id: 'diamond', name: 'Diamond', logo: '/images/brands/diamond.png', description: 'Shine like a diamond with our paints', productCount: 35 },
  { id: 'gobis', name: "Gobi's", logo: '/images/brands/gobi\'s.png', description: 'Traditional quality, modern finish', productCount: 22 },
  { id: 'ocean', name: 'Ocean', logo: '/images/brands/ocean.png', description: 'Deep colors inspired by the ocean', productCount: 18 },
  { id: 'reliable', name: 'Reliable', logo: '/images/brands/reliable.png', description: 'Reliability you can trust', productCount: 25 },
  { id: 'reliance', name: 'Reliance', logo: '/images/brands/reliance.png', description: 'Building trust through quality', productCount: 20 },
  { id: 'rozzi', name: 'Rozzi', logo: '/images/brands/rozzi.png', description: 'Italian-inspired elegance', productCount: 15 },
  { id: 'saasi', name: 'Saasi', logo: '/images/brands/saasi.png', description: 'Colors that speak for themselves', productCount: 30 },
];

export const categories: Category[] = [
  {
    id: 'decorative',
    name: 'Decorative',
    slug: 'decorative',
    image: '/images/categories/decorative.jpg',
    description: 'Transform your interiors with our premium decorative paints. Perfect for walls, ceilings, and accent features.',
    productCount: 120,
  },
  {
    id: 'industrial',
    name: 'Industrial',
    slug: 'industrial',
    image: '/images/categories/industrial.jpg',
    description: 'Heavy-duty industrial coatings for factories, warehouses, and commercial spaces.',
    productCount: 85,
  },
  {
    id: 'auto',
    name: 'Auto',
    slug: 'auto',
    image: '/images/categories/Auto-Finish.jpg',
    description: 'Professional automotive finishes for cars, bikes, and all vehicles.',
    productCount: 65,
  },
  {
    id: 'projects',
    name: 'Projects',
    slug: 'projects',
    image: '/images/categories/project.png',
    description: 'Complete paint solutions for construction projects and large-scale applications.',
    productCount: 95,
  },
];

export const products: Product[] = [
  // Berger Products
  {
    id: 'berger-elegance-emulsion',
    name: 'Elegance Emulsion',
    brand: 'Berger',
    category: 'decorative',
    price: 4500,
    originalPrice: 5200,
    image: '/images/products/berger/elegance emulsion.png',
    description: 'Premium interior emulsion with silky smooth finish',
    coverage: '120-140 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 45,
  },
  {
    id: 'berger-silk-emulsion',
    name: 'Silk Emulsion',
    brand: 'Berger',
    category: 'decorative',
    price: 5200,
    originalPrice: 5800,
    image: '/images/products/berger/silk emulsion.png',
    description: 'Luxurious silk finish for elegant interiors',
    coverage: '100-120 sq ft/liter',
    finishType: 'Silk',
    inStock: true,
    loyaltyPoints: 52,
  },
  {
    id: 'berger-weather-coat',
    name: 'Weather Coat Glow 365',
    brand: 'Berger',
    category: 'decorative',
    price: 6500,
    image: '/images/products/berger/weather coat glow 365.webp',
    description: 'All-weather exterior paint with UV protection',
    coverage: '80-100 sq ft/liter',
    finishType: 'Gloss',
    inStock: true,
    loyaltyPoints: 65,
  },
  {
    id: 'berger-super-gloss-enamel',
    name: 'Super Gloss Enamel',
    brand: 'Berger',
    category: 'decorative',
    price: 3800,
    image: '/images/products/berger/super gloss enamel.png',
    description: 'High gloss enamel for wood and metal surfaces',
    coverage: '130-150 sq ft/liter',
    finishType: 'High Gloss',
    inStock: true,
    loyaltyPoints: 38,
  },
  {
    id: 'berger-red-oxide-primer',
    name: 'Red Oxide Primer',
    brand: 'Berger',
    category: 'industrial',
    price: 2800,
    image: '/images/products/berger/Red-Oxide-Primer.webp',
    description: 'Anti-corrosive primer for metal surfaces',
    coverage: '100-120 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 28,
  },
  {
    id: 'berger-woodpro-lacquer',
    name: 'WoodPro PU Lacquer',
    brand: 'Berger',
    category: 'decorative',
    price: 4200,
    image: '/images/products/berger/woodpro pu lacquer.webp',
    description: 'Premium polyurethane lacquer for wood finishing',
    coverage: '140-160 sq ft/liter',
    finishType: 'Gloss',
    inStock: true,
    loyaltyPoints: 42,
  },
  {
    id: 'berger-aluminum-paint',
    name: 'Aluminum Paint',
    brand: 'Berger',
    category: 'industrial',
    price: 3200,
    image: '/images/products/berger/Aluminum-Paint.webp',
    description: 'Heat-resistant aluminum paint for industrial use',
    coverage: '80-100 sq ft/liter',
    finishType: 'Metallic',
    inStock: true,
    loyaltyPoints: 32,
  },
  {
    id: 'berger-chlorinated-rubber',
    name: 'Chlorinated Rubber Base Paint',
    brand: 'Berger',
    category: 'industrial',
    price: 5500,
    image: '/images/products/berger/Chlorinated-Rubber-Base-Paint.webp',
    description: 'Chemical-resistant coating for industrial floors',
    coverage: '60-80 sq ft/liter',
    finishType: 'Semi-Gloss',
    inStock: true,
    loyaltyPoints: 55,
  },
  // Diamond Products
  {
    id: 'diamond-ace-emulsion',
    name: 'Ace Acrylic Plastic Emulsion',
    brand: 'Diamond',
    category: 'decorative',
    price: 3500,
    image: '/images/products/diamond/ace acrylic-plastic-emulsion.webp',
    description: 'Durable acrylic emulsion for interior walls',
    coverage: '120-140 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 35,
  },
  {
    id: 'diamond-ace-durasilk',
    name: 'Ace Durasilk Emulsion',
    brand: 'Diamond',
    category: 'decorative',
    price: 4800,
    image: '/images/products/diamond/ace Durasilk emulsion.webp',
    description: 'Silk finish emulsion with superior washability',
    coverage: '100-120 sq ft/liter',
    finishType: 'Silk',
    inStock: true,
    loyaltyPoints: 48,
  },
  {
    id: 'diamond-weather-defender',
    name: 'Ace Weather Defender',
    brand: 'Diamond',
    category: 'decorative',
    price: 5800,
    image: '/images/products/diamond/ace weather defender.webp',
    description: 'Premium exterior paint with weather protection',
    coverage: '80-100 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 58,
  },
  {
    id: 'diamond-super-gloss',
    name: 'Ace Super Gloss Enamel',
    brand: 'Diamond',
    category: 'decorative',
    price: 3200,
    image: '/images/products/diamond/ace super gloss enamel.webp',
    description: 'Premium gloss enamel for wood and metal',
    coverage: '130-150 sq ft/liter',
    finishType: 'High Gloss',
    inStock: true,
    loyaltyPoints: 32,
  },
  {
    id: 'diamond-roof-coat',
    name: 'Roof Coat',
    brand: 'Diamond',
    category: 'industrial',
    price: 4500,
    image: '/images/products/diamond/roof coat.webp',
    description: 'Waterproof coating for roof surfaces',
    coverage: '50-60 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 45,
  },
  // Ocean Products
  {
    id: 'ocean-emulsion',
    name: 'Ocean Emulsion',
    brand: 'Ocean',
    category: 'decorative',
    price: 2800,
    image: '/images/products/ocean/ocean emulsion.png',
    description: 'Affordable quality emulsion for interiors',
    coverage: '120-140 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 28,
  },
  {
    id: 'ocean-lustre-enamel',
    name: 'Ocean Lustre Enamel',
    brand: 'Ocean',
    category: 'decorative',
    price: 2500,
    image: '/images/products/ocean/ocean Lustre-enamel.png',
    description: 'Lustrous enamel for smooth finishes',
    coverage: '130-150 sq ft/liter',
    finishType: 'Semi-Gloss',
    inStock: true,
    loyaltyPoints: 25,
  },
  {
    id: 'ocean-metallic-enamel',
    name: 'Ocean Metallic Enamel',
    brand: 'Ocean',
    category: 'auto',
    price: 3500,
    image: '/images/products/ocean/ocean metallic enamel.png',
    description: 'Metallic finish enamel for automotive use',
    coverage: '100-120 sq ft/liter',
    finishType: 'Metallic',
    inStock: true,
    loyaltyPoints: 35,
  },
  {
    id: 'ocean-red-oxide',
    name: 'Ocean Red Oxide Primer',
    brand: 'Ocean',
    category: 'industrial',
    price: 2200,
    image: '/images/products/ocean/ocean RED oxide primer.png',
    description: 'Protective primer for metal surfaces',
    coverage: '100-120 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 22,
  },
  // Reliance Products
  {
    id: 'reliance-semi-plastic',
    name: 'Reliance Semi Plastic Emulsion',
    brand: 'Reliance',
    category: 'decorative',
    price: 2600,
    image: '/images/products/reliance/Reliance-Semi-Plastic-Emulsion.png',
    description: 'Economy emulsion with good coverage',
    coverage: '120-140 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 26,
  },
  {
    id: 'reliance-weather-guard',
    name: 'Reliance Weather Guard',
    brand: 'Reliance',
    category: 'decorative',
    price: 4200,
    image: '/images/products/reliance/Reliance-Weather-Guard.png',
    description: 'Weather-resistant exterior paint',
    coverage: '80-100 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 42,
  },
  {
    id: 'reliance-matt-enamel',
    name: 'Reliance Matt Enamel',
    brand: 'Reliance',
    category: 'decorative',
    price: 2800,
    image: '/images/products/reliance/Reliance-Matt-Enamel.png',
    description: 'Matt finish enamel for wood and metal',
    coverage: '130-150 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 28,
  },
  {
    id: 'reliance-red-oxide',
    name: 'Reliance Red Oxide Primer',
    brand: 'Reliance',
    category: 'industrial',
    price: 2000,
    image: '/images/products/reliance/Reliance-Red-Oxide-Primer.png',
    description: 'Anti-rust primer for iron and steel',
    coverage: '100-120 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 20,
  },
];

export const WHATSAPP_NUMBER = '923001234567'; // Replace with actual number

export const loyaltyTiers = {
  bronze: { min: 0, max: 999, discount: 2, pointMultiplier: 1 },
  silver: { min: 1000, max: 4999, discount: 5, pointMultiplier: 1.25 },
  gold: { min: 5000, max: 9999, discount: 8, pointMultiplier: 1.5 },
  platinum: { min: 10000, max: Infinity, discount: 12, pointMultiplier: 2 },
};
